### PR TITLE
Fix trapezoid decomposition edge sorting for coincident-x edges

### LINKED ISSUE #694: Profile and refactor polygon Boolean
`modmesh::detail::compute_boolean_with_decomposition()` (in [`polygon.hpp:2847`](https://github.com/solvcon/modmesh/blob/3ea2820120bbd505132d9696e1cc85a627d506d6/cpp/modmesh/universe/polygon.hpp#L2847)) has potential performance hotspots of creating lambda closure [`find_crossing()`](https://github.com/solvcon/modmesh/blob/3ea2820120bbd505132d9696e1cc85a627d506d6/cpp/modmesh/universe/polygon.hpp#L2963) in nested tight loops.  It is also too long (300+ lines).

Profile to confirm or falsify performance concerns.  Significant mockup data need to be created for meaningful profiling.

The helper function also overuses lambdas.  The helper function (`compute_boolean_with_decomposition()`) should be refactored to a helper class, moved to standalone files (outside `polygon.hpp`), and all lambdas should be turned into member functions.

This issue is to track the work mentioned in https://github.com/solvcon/modmesh/pull/693#discussion_r2935262981.

### PR DESCRIPTION
**Pull request by tigercosmos**
When two edges share the same x-coordinate at the current sweep line (e.g., at a triangle apex), the sort was unstable and could produce inverted trapezoids where left_x > right_x. Break ties by comparing dxdy so the left-leaning edge always comes first.

Add test_decomposition_edge_order to verify no inverted trapezoids are produced when decomposing triangles with shared apex y-values.

## Before & After

Before: the union and difference are incorrect (the bottom parts).

**union**
Screenshot 2026-03-18 at 4 04 14 PM
**difference**
Screenshot 2026-03-18 at 4 04 21 PM

After: now the union and difference are correct.

**union**
Screenshot 2026-03-19 at 8 33 37 PM
**difference**
Screenshot 2026-03-19 at 8 33 45 PM

## AI Tool

Claude Code with Opus 4.6 for draft. All code, commit and test cases are manually checked and modified.

### CODE REVIEW

File: cpp/modmesh/universe/polygon.hpp [hunk 1]
```diff
@@ -1145,9 +1145,14 @@ std::pair<size_t, size_t> TrapezoidalDecomposer<T>::decompose(size_t polygon_id,
...
-                          value_type bx = b.x_at_lower_y + b.dxdy * (y_current - b.lower_y);
-                          return ax < bx; });
+                      value_type ax = a.x_at_lower_y + a.dxdy * (y_current - a.lower_y);
+                      value_type bx = b.x_at_lower_y + b.dxdy * (y_current - b.lower_y);
+                      if (ax != bx)
+                      {
+                          return ax < bx;
+                      }
+                      // If x values are equal, sort by dxdy to ensure consistent ordering of edges
+                      return a.dxdy < b.dxdy; });
```
Comment (tigercosmos) [inline cpp/modmesh/universe/polygon.hpp:1155]: Meat

File: tests/test_polygon3d.py [hunk 2]
```diff
@@ -761,9 +761,45 @@ def test_boolean_concave_polygon(self):
...
+            self.assertLessEqual(
+                trap_pad.x3(trap_id), trap_pad.x2(trap_id),
+                f"Inverted trapezoid {trap_id}:"
+                f"top-left x={trap_pad.x3(trap_id)}"
+                f" > top-right x={trap_pad.x2(trap_id)}")
+
     def test_boolean_result_ccw_winding(self):
         """Test that all result polygons from boolean operations have
-        counter-clockwise winding (non-negative signed area)."""
+        counter - clockwise winding(non - negative signed area)."""
```
Comment (tigercosmos) [inline tests/test_polygon3d.py:802]: piggypack format fix.

**Comment by tigercosmos** [comment]
@yungyuc  please take a look.

**Comment by tigercosmos** [comment]
The failed CI is due to other system issues.

File: tests/test_polygon3d.py [hunk 3]
```diff
@@ -761,9 +761,45 @@ def test_boolean_concave_polygon(self):
...
 
+    def test_decomposition_edge_order(self):
+        """Test that polygon decomposition produces non-inverted trapezoids.
+        """
+        pad = self.PolygonPad(ndim=2)
+
+        # Triangle 1: apex at bottom y=0, base at y=2
+        # Vertices CCW: (0,2) -> (4,2) -> (2,0)
+        nodes1 = [
+            self.Point(0.0, 2.0, 0.0),
```
Comment (yungyuc) [inline tests/test_polygon3d.py:772]: The fixtures do not look like [the screenshots you took](https://github.com/solvcon/modmesh/pull/697#issue-4101094702), which have more detail.  Could you please elaborate how you created the test cases and screenshots?

**Review by yungyuc — COMMENTED** [review]
The code looks good but please clarify your test cases and screenshots.

- [x] You screenshots contain UI that I am not familiar with.  Please share how to operate pilot get get them.  We should consider including the related automation with the PR or a later one.
- [x] Discuss whether to include the screenshots data in test cases.

File: tests/test_polygon3d.py (hunk 3 above)
Comment (tigercosmos) [reply tests/test_polygon3d.py:772]: @yungyuc  Sorry to be unclear. The PR demo is for pointing out the issue, so it uses a different SVG file. 
Here is the visualization of the fixtures in this test case, and you can see the result is correct now.

**Before**
Screenshot 2026-03-20 at 2 29 23 PM


**After**
Screenshot 2026-03-20 at 2 23 15 PM

> For the visualization code, you can refer to https://github.com/solvcon/modmesh/pull/699. It's just AI generated one-time purpose code.

**Comment by tigercosmos** [comment]
@yungyuc  please check again. Thanks!

File: tests/test_polygon3d.py (hunk 3 above)
Comment (yungyuc) [reply tests/test_polygon3d.py:772]: The tests are good.

**Review by yungyuc — APPROVED** [review]
The fix and the test are good.

The prototype Boolean GUI is also good.  It's time to move on to improve the GUI part.  It will speed up the development.
