### PR TITLE
fix `make pyprof` hang issue

### LINKED ISSUE #635: `make pyprof` runs super slow on `macos-15` GA runner
PR #634 temporarily turns off `make pyprof` step in `build_macos-15_Release` because one or more profiling scripts takes super long time, like hours:

```
Run make pyprof
  make pyprof
  shell: /bin/bash -e {0}
  env:
    QT_DEBUG_PLUGINS: 1
    PIP_BREAK_SYSTEM_PACKAGES: 1
    AQT_CONFIG: thirdparty/aqt_settings.ini
    PKG_CONFIG_PATH: /Users/runner/work/modmesh/Qt/6.8.1/macos/lib/pkgconfig
    QT_ROOT_DIR: /Users/runner/work/modmesh/Qt/6.8.1/macos
    QT_PLUGIN_PATH: /Users/runner/work/modmesh/Qt/6.8.1/macos/plugins
    QML2_IMPORT_PATH: /Users/runner/work/modmesh/Qt/6.8.1/macos/qml
cmake --build build/dev314 --target _modmesh_py VERBOSE= -j
[ 96%] Built target modmesh_primary
[100%] Built target _modmesh
[100%] Built target _modmesh_py
/opt/homebrew/bin/python3 profiling/profile_arithmetic_simd.py > profiling/results/profile_arithmetic_simd.output
/Users/runner/work/modmesh/modmesh/profiling/profile_arithmetic_simd.py:111: RuntimeWarning: divide by zero encountered in divide
  return np.divide(src1, src2)
/opt/homebrew/bin/python3 profiling/profile_arithmetic.py > profiling/results/profile_arithmetic.output
/opt/homebrew/bin/python3 profiling/profile_median.py > profiling/results/profile_median.output
/opt/homebrew/bin/python3 profiling/profile_statistic_ops.py > profiling/results/profile_statistic_ops.output
Matplotlib is building the font cache; this may take a moment.
/opt/homebrew/bin/python3 profiling/profile_take_along_axis.py > profiling/results/profile_take_along_axis.output
Error: The operation was canceled.
```

@KHLee529 [suggested](https://github.com/solvcon/modmesh/pull/634#issuecomment-3549993190):

> From the error message it seems like that `profile_take_along_axis.py` is the script that cause infinite run. Could you please try to first remove this script by renaming it to any name without prefix `profile_`?

We need to fix the bad profiling script (or SIMD code).

### PR DESCRIPTION
**Pull request by nccvector**
## Relates to & fixes Issue
https://github.com/solvcon/modmesh/issues/635

## Overview
This PR contains safe guards for:
- passing empty list [] to SimpleArray
- array large enough for simd in `check_between` function in `neon.hpp` <- (array size can be incompatible with neon simd lane size causing a segfault)

# How I discovered a solution
Out of curiosity I just created the gtest to test the `take_along_axis_simd` function directly and found segfaults. I just fixed the segfaults and ran `make pyprof` again just to see what happens and I observed that `make pyprof` no longer hanged.

# I tried to reproduce the hang
Then I got curious and tried to reproduce the bug so I:
- removed the segfault safeguards (reverted my changes)
- Then I created a new python script to reproduce the hanging issue and called the simd function, but it still did not hang (gave the same segfault as gtest does)
- Then I added the `modmesh.call_profiler` similar to the actual profiling script and viola it hanged.

So to reproduce you need:
- a segfault
- python script with profiler

# More info
It seems passing the array smaller than N_lane size causes infinite recursion (because the first for loop is skipped but there is a recursive call right below that loop which calls the function again with the same array). That infinite recursion leads to stack corruption which causes the segfault. I still have not confirmed why running under profiler makes any difference.

### CODE REVIEW

File: cpp/modmesh/buffer/SimpleArray.hpp [hunk 1]
```diff
@@ -1874,6 +1874,11 @@ A detail::SimpleArrayMixinSort<A, T>::take_along_axis_simd(SimpleArray<I> const
                                              << " but the array is " << athis->ndim() << " dimension");
     }
 
+    if (indices.size() == 0)
+    {
+        return A(indices.shape());
+    }
+
```
Comment (nccvector) [inline cpp/modmesh/buffer/SimpleArray.hpp:1881]: Unrelated: Fixes segfault if we pass empty list [] (unrelated edge case, not the meat of this PR)

File: cpp/modmesh/simd/neon/neon.hpp [hunk 2]
```diff
@@ -115,6 +115,13 @@ const T * check_between(T const * start, T const * end, T const & min_val, T con
     T const * ret = NULL;
 
     T const * ptr = start;
+
+    // Check if array is large enough for SIMD processing
+    if (end - start < N_lane)
+    {
+        return generic::check_between<T>(start, end, min_val, max_val);
+    }
+
```
Comment (nccvector) [inline cpp/modmesh/simd/neon/neon.hpp:124]: Meat of this PR: if the array is smaller than lane size then the loop below goes on forever

File: gtests/CMakeLists.txt [hunk 3]
```diff
@@ -46,3 +46,19 @@ gtest_discover_tests(test_nopython)
...
+    test_take_along_axis_simd_native.cpp
+    ${MODMESH_TOGGLE_SOURCES}
+    ${MODMESH_BUFFER_SOURCES}
+    ${MODMESH_SIMD_SOURCES}
+)
+
+target_link_libraries(
+    test_take_along_axis_simd_native
+    GTest::gtest_main
+)
```
Comment (nccvector) [inline gtests/CMakeLists.txt]: I just thought it might be a good idea to add gtest to test the code directly without bindings first

**Comment by yungyuc** [comment]
Thank you, @nccvector , when you are ready for review, please also turn the profiling run back on (reverting change in PR #634).

**Comment by KHLee529** [comment]
Cool, so the reason of infinite run is actually segmentation fault? I'll wait for the description for more details.

File: cpp/modmesh/buffer/SimpleArray.hpp (hunk 1 above)
Comment (tigercosmos) [reply cpp/modmesh/buffer/SimpleArray.hpp:1881]: It's nice to just but I wonder if we should raise directly?

File: cpp/modmesh/simd/neon/neon.hpp (hunk 2 above)
Comment (tigercosmos) [reply cpp/modmesh/simd/neon/neon.hpp:124]: why not return error directly? Also I wonder why this can ever happen because we have checked the alignment using `check_alignment`?

File: cpp/modmesh/buffer/SimpleArray.hpp (hunk 1 above)
Comment (yungyuc) [reply cpp/modmesh/buffer/SimpleArray.hpp:1881]: It makes sense to pass this corner case silently because empty input should be equivalent to no-op.  No-op should not throw exception.

File: cpp/modmesh/simd/neon/neon.hpp (hunk 2 above)
Comment (yungyuc) [reply cpp/modmesh/simd/neon/neon.hpp:124]: A single element in an array and having less elements in a vector register (or a cache line) are valid input, especially for very wide cache line or stream processor.  We may choose to process it with SIMD or not, but it must work.

**Comment by nccvector** [comment]
> Cool, so the reason of infinite run is actually segmentation fault? I'll wait for the description for more details.

Segfault + Profiler

File: gtests/CMakeLists.txt (hunk 3 above)
Comment (yungyuc) [reply gtests/CMakeLists.txt]: I concur.

File: cpp/modmesh/simd/neon/neon.hpp [hunk 4]
```diff
@@ -115,6 +115,13 @@ const T * check_between(T const * start, T const * end, T const & min_val, T con
     T const * ret = NULL;
 
     T const * ptr = start;
+
+    // Check if array is large enough for SIMD processing
```
Comment (yungyuc) [inline cpp/modmesh/simd/neon/neon.hpp:119]: This prevents wrong counting when the number of elements is less than a SIMD vector width for `check_between()` (vector mode).

I am curious whether this issue is also in other vector-mode calculating functions?  @KHLee529 what do you think?

File: gtests/CMakeLists.txt [hunk 5]
```diff
@@ -46,3 +46,19 @@ gtest_discover_tests(test_nopython)
 add_custom_target(run_gtest
     COMMAND $<TARGET_FILE:test_nopython>
     DEPENDS test_nopython)
+
+# New binary target for testing take_along_axis_simd directly from C++
```
Comment (yungyuc) [inline gtests/CMakeLists.txt]: Why do you need a new binary instead of using [`test_nopython` at L48](https://github.com/solvcon/modmesh/pull/641/files#diff-d7873e4ae849e77b02084c569b8d18ff4037158430e93f47869159c273a97b64R48) above?

**Review by yungyuc — CHANGES_REQUESTED** [review]
This is a good fix.  Thank you, @nccvector.

One point to discuss:
- [x] Why create a new binary instead of using the existing `test_nopython`?

Review protocol reminder: please leave a global comment to request for a next review, and use the inline comments (annotations) to discuss each of the points.

**Comment by tychuang1211** [comment]
https://github.com/nccvector/modmesh/blob/f485c5292821d784334031f0cce01402adce4442/tests/test_buffer.py#L1020
Would you like fix the typo here as well?

**Comment by yungyuc** [comment]
> https://github.com/nccvector/modmesh/blob/f485c5292821d784334031f0cce01402adce4442/tests/test_buffer.py#L1020 Would you like fix the typo here as well?

Good catch, @tychuang1211 .  Feel free to fix the existing code in a separate PR.

File: cpp/modmesh/simd/neon/neon.hpp [hunk 6]
```diff
@@ -115,6 +115,13 @@ const T * check_between(T const * start, T const * end, T const & min_val, T con
...
+    if (end - start < N_lane)
+    {
+        return generic::check_between<T>(start, end, min_val, max_val);
+    }
+
     for (; ptr <= end - N_lane; ptr += N_lane)
```
Comment (KHLee529) [inline cpp/modmesh/simd/neon/neon.hpp:125]: @nccvector I'm wondering, why this for loop is not skipped if `end - start < N_lane`.

Comment (KHLee529) [reply cpp/modmesh/simd/neon/neon.hpp:125]: > I am curious whether this issue is also in other vector-mode calculating functions? @KHLee529 what do you think?

@yungyuc To answer your question in another comment, I found this point a bit strange. This loop should be skip if the amount of array elements between `ptr`, which is equal to `start`, and `end` is less than `N_lane`. I did this in every other vector computation. Therefore if `check_between` may cause segmentation fault, others may do so, too.

**Comment by KHLee529** [comment]
> * Then I added the modmesh.call_profiler similar to the actual profiling script and viola it hanged.

@nccvector did you find the reason why the application wont just crash when call_profiler is used?

**Comment by nccvector** [comment]
> > * Then I added the modmesh.call_profiler similar to the actual profiling script and viola it hanged.
> 
> @nccvector did you find the reason why the application wont just crash when call_profiler is used?

Sorry I have been away for a while, will check today or over the weekend

File: cpp/modmesh/simd/neon/neon.hpp (hunk 6 above)
Comment (nccvector) [reply cpp/modmesh/simd/neon/neon.hpp:125]: @KHLee529 the loop gets skipped but below this loop there is a recursive call under `if(ptr != end)` condition which calls this function again with the same array. If we pass an array of size 1 (which is N_lane=2) we run into an infinite recursion. Now I am trying to figure out why this results in a segfault consistently (possible stack corruption?)

File: gtests/CMakeLists.txt (hunk 5 above)
Comment (nccvector) [reply gtests/CMakeLists.txt]: Sorry I missed that. Making the change

File: cpp/modmesh/simd/neon/neon.hpp (hunk 6 above)
Comment (nccvector) [reply cpp/modmesh/simd/neon/neon.hpp:125]: The use of recursion also seems unnecessary here, we can refactor a bit and avoid recursion altogether

File: gtests/CMakeLists.txt (hunk 5 above)
Comment (nccvector) [reply gtests/CMakeLists.txt]: Done

File: cpp/modmesh/simd/neon/neon.hpp (hunk 6 above)
Comment (yungyuc) [reply cpp/modmesh/simd/neon/neon.hpp:125]: Good catch!  My bad that I did not notice the recursion.  I concur.  Recursion should not be used here.  High-performance code should exclusively use loop so that it will be more straight-forward to check the assembly generated.

> The use of recursion also seems unnecessary here, we can refactor a bit and avoid recursion altogether

Agree.  Let's make it a separate task.  I can find time to create an issue to track it, but anyone is welcome to create one.

File: gtests/CMakeLists.txt (hunk 5 above)
Comment (yungyuc) [reply gtests/CMakeLists.txt]: Cool

**Review by yungyuc — APPROVED** [review]
LGTM

@nccvector this is a ~~small~~ straight-forward change and is suitable to be squashed into a single commit.  Do you want to do it before I merge?

**Comment by yungyuc** [comment]
> > > * Then I added the modmesh.call_profiler similar to the actual profiling script and viola it hanged.
> > 
> > 
> > @nccvector did you find the reason why the application wont just crash when call_profiler is used?
> 
> Sorry I have been away for a while, will check today or over the weekend

This is an interesting point.  If github is not the best place for brainstorming, we can also discuss on discord: https://discord.com/channels/730297880140578906/730393342818648204/1446289303864086601

File: cpp/modmesh/simd/neon/neon.hpp (hunk 2 above)
Comment (tychuang1211) [reply cpp/modmesh/simd/neon/neon.hpp:124]: Why can't we just replace line 138 with `return generic::check_between<T>(start, end, min_val, max_val);`?

**Comment by nccvector** [comment]
> LGTM
> 
> @nccvector this is a ~small~ straight-forward change and is suitable to be squashed into a single commit. Do you want to do it before I merge?

Squashed, now its one commit 👍

File: cpp/modmesh/simd/neon/neon.hpp (hunk 6 above)
Comment (KHLee529) [reply cpp/modmesh/simd/neon/neon.hpp:125]: Oh my god, this is my fault. What I wanted to do was `generic::check_between` instead of `check_between`. The recursion is not intended. You can refer to the arithmetic operations below, they are correct.

In this case, I would suggest fix this issue by simply replace `check_between` by `generic::check_between` at L145. That would make more sense to me.

File: cpp/modmesh/simd/neon/neon.hpp (hunk 2 above)
Comment (KHLee529) [reply cpp/modmesh/simd/neon/neon.hpp:124]: > Why can't we just replace line 138 with `return generic::check_between<T>(start, end, min_val, max_val);`?

This is exactly the way I suggest to fix this issue.

**Review by KHLee529 — CHANGES_REQUESTED** [review]
- [ ] Fix this issue by change the `check_between` to `generic::check_between` in L138 (L145 in current context)

**Comment by yungyuc** [comment]
> > LGTM
> > @nccvector this is a ~small~ straight-forward change and is suitable to be squashed into a single commit. Do you want to do it before I merge?
> 
> Squashed, now its one commit 👍

Wonderful.  Merged.

**Comment by yungyuc** [comment]
> * [ ]  Fix this issue by change the `check_between` to `generic::check_between` in L138 (L145 in current context)

Good catch.  @KHLee529 , please create an issue to track the fix.

**Comment by tigercosmos** [comment]
@nccvector  Good job!

**Comment by KHLee529** [comment]
@nccvector nice job!

**Comment by KHLee529** [comment]
> > * [ ]   Fix this issue by change the `check_between` to `generic::check_between` in L138 (L145 in current context)
> 
> Good catch. @KHLee529 , please create an issue to track the fix.

Issue #646 is created to track this fix.
