### PR TITLE
Fix: Support to assign the complex number to SimpleArray

### LINKED ISSUE #604: SimpleArrayComplex128[i] = numpy.complex128 fails with cast error
#### How to reproduce

```python
import modmesh as mm
import numpy as np

nc = np.array([1.0 + 0.1j])
mc = mm.SimpleArrayComplex128([1])
mc[0] = nc[0]          # <- fails

print(mc[0].real, mc[0].imag)
```

#### Actual

```
Traceback (most recent call last):
  ...
  mc[0] = nc[0]
RuntimeError: Unable to cast Python instance of type <class 'numpy.complex128'> to C++ type '?' 
(#define PYBIND11_DETAILED_ERROR_MESSAGES or compile in debug mode for details)
```

#### Expected

`mc[0]` should accept a `numpy.complex128` (and Python `complex`) and store it as `modmesh::Complex<double>` without extra wrapping.

#### Notes

* If we add additional initializer in `WrapComplex.cpp`:
 ```c++
            .def(
                py::init(
                    [](const std::complex<value_type> & c)
                    { return std::make_shared<wrapped_type>(wrapped_type{c.real(), c.imag()}); }),
                py::arg("np_complex"))
```

Constructing `mm.complex128` from a Python/numpy complex could work, but assigning an element to `SimpleArrayComplex128` doesn't work.
```python
  mc = mm.complex128(np.complex128(1+0.1j))  # ok
  print(mc.real, mc.imag) # 1 0.1j
  ma = mm.SimpleArrayComplex128([1]) #ok  
  mc[0] = np.complex128(1+0.1j) # not ok
```

### PR DESCRIPTION
**Pull request by ThreeMonth03**
## Problem
In issue #604 , when we assign values from `np.complex128` or `Complex` to `SimpleArrayComplex128`, the cast of python instance fails.

```python
import modmesh as mm
import numpy as np

nc = np.array([1.0 + 0.1j])
mc = mm.SimpleArrayComplex128([1])
mc[0] = nc[0]          # <- fails

print(mc[0].real, mc[0].imag)
```

```shell
Traceback (most recent call last):
  ...
  mc[0] = nc[0]
RuntimeError: Unable to cast Python instance of type <class 'numpy.complex128'> to C++ type '?' 
(#define PYBIND11_DETAILED_ERROR_MESSAGES or compile in debug mode for details)
```

## Solution
The function `__setitem__` in `wrap_SimpleArray.cpp` `calls &property_helper::setitem_parser`, and the fuunction `calls &property_helper::setitem_parser` checks if the value is number based on the following logic:

```c++
const bool is_number = py::isinstance<py::bool_>(py_value) || py::isinstance<py::int_>(py_value) || py::isinstance<py::float_>(py_value) || is_complex_v<T>;
```

This condition ignores whether `py_value` is `np.complex128` or `Complex`, it just check whether `py_value` is `modmesh.complex128`.

### CODE REVIEW

File: cpp/modmesh/buffer/pymod/array_common.hpp [hunk 1]
```diff
@@ -211,21 +211,39 @@ class ArrayPropertyHelper
...
                 const auto key = py_key.cast<ssize_t>();
-
+                if constexpr (is_complex_v<T>)
+                {
+                    if (py::isinstance(py_value, complex_class))
+                    {
+                        arr_out.at(key) = py_value.cast<std_complex_t<T>>();
+                        return;
+                    }
+                }
```
Comment (ThreeMonth03) [inline cpp/modmesh/buffer/pymod/array_common.hpp]: When `py_value` is `Complex` or `np.complex`, casting to std::complex at first.

File: cpp/modmesh/math/Complex.hpp [hunk 2]
```diff
@@ -261,6 +269,23 @@ struct is_complex<Complex<T>> : std::true_type {};
...
+{
+    using type = T;
+};
+
+template <typename T>
+using complex_element_type_t = typename complex_element_type<T>::type;
+
+template <typename T>
+using std_complex_t = std::complex<complex_element_type_t<T>>;
+
```
Comment (ThreeMonth03) [inline cpp/modmesh/math/Complex.hpp]: Given the type of `complex<T>`, return `std::complex<T>`

File: cpp/modmesh/math/pymod/wrap_Complex.cpp [hunk 3]
```diff
@@ -106,6 +106,11 @@ class MODMESH_PYTHON_WRAPPER_VISIBILITY WrapComplex
             .def_readonly("imag", &wrapped_type::imag_v)
             .def("norm", &wrapped_type::norm)
             .def("conj", &wrapped_type::conj)
+            .def("__complex__",
+                 [](const wrapped_type & self)
+                 {
+                     return self.to_std_complex();
+                 })
```
Comment (ThreeMonth03) [inline cpp/modmesh/math/pymod/wrap_Complex.cpp:113]: Add an interface to support casting.

**Review by ThreeMonth03 — COMMENTED** [review]
@yungyuc @tigercosmos Please review this pull request. Thanks.

File: cpp/modmesh/buffer/pymod/array_common.hpp (hunk 1 above)
Comment (yungyuc) [reply cpp/modmesh/buffer/pymod/array_common.hpp]: The if/else code is unbalanced and hard to read:

```cpp
if constexpr (is_complex_v<T>)
{
    if (py::isinstance(py_value, complex_class))
    {
        arr_out.at(key) = py_value.cast<std_complex_t<T>>();
        return;
    }
}
arr_out.at(key) = py_value.cast<T>();
return;
```

The following code is more concise and maintainable:

```cpp
if (is_complex_v<T> && py::isinstance(py_value, complex_class))
{
    arr_out.at(key) = py_value.cast<std_complex_t<T>>();
}
else
{
    arr_out.at(key) = py_value.cast<T>();
}
```

`constexpr` is unnecessary because `py::isinstance(py_value, complex_class)` needs to happen during runtime rather than compile time.

**Review by yungyuc — CHANGES_REQUESTED** [review]
Good job.  Points to address:

- [x] Balance the if/else to improve readability for the value assignment.
- [x] Write an informative summary in the commit log.

File: cpp/modmesh/buffer/pymod/array_common.hpp (hunk 1 above)
Comment (ThreeMonth03) [reply cpp/modmesh/buffer/pymod/array_common.hpp]: However, the program will return compile error if we don't use `if constexpr`.
```c++
template <typename T>
struct complex_element_type
{
};

template <typename T>
struct complex_element_type<Complex<T>>
{
    using type = T;
};

template <typename T>
using complex_element_type_t = typename complex_element_type<T>::type;

template <typename T>
using std_complex_t = std::complex<complex_element_type_t<T>>;
```

The following message is compile error.
```shell
/home/threemonth03/Downloads/modmesh/cpp/modmesh/buffer/pymod/wrap_SimpleArrayPlex.cpp:325:55:   required from here
/home/threemonth03/Downloads/modmesh/cpp/modmesh/math/Complex.hpp:287:7: error: no type named ‘type’ in ‘struct modmesh::complex_element_type<double>’
In file included from /home/threemonth03/Downloads/modmesh/cpp/modmesh/math/math.hpp:8,
                 from /home/threemonth03/Downloads/modmesh/cpp/modmesh/buffer/SimpleArray.hpp:32,
                 from /home/threemonth03/Downloads/modmesh/cpp/modmesh/buffer/buffer.hpp:38,
                 from /home/threemonth03/Downloads/modmesh/cpp/modmesh/toggle/toggle.hpp:32,
                 from /home/threemonth03/Downloads/modmesh/cpp/modmesh/python/common.hpp:38,
                 from /home/threemonth03/Downloads/modmesh/cpp/modmesh/buffer/pymod/buffer_pymod.hpp:34,
                 from /home/threemonth03/Downloads/modmesh/cpp/modmesh/buffer/pymod/wrap_SimpleArray.cpp:29:
```

Comment (yungyuc) [reply cpp/modmesh/buffer/pymod/array_common.hpp]: Interesting.  Please figure out why.

Comment (ThreeMonth03) [reply cpp/modmesh/buffer/pymod/array_common.hpp]: > Interesting. Please figure out why.

The error message is simple, it caused from the missing alias in generic template.
```c++
template <typename T>
struct complex_element_type
{
};
```

However, if we add the alias `using type = T;` in generic template, it would deduce to a wrong type, so I think I should redesign the template , such that it might look like `using convert_to_std_t = something...;`.

File: cpp/modmesh/buffer/pymod/array_common.hpp [hunk 4]
```diff
@@ -174,6 +174,21 @@ inline modmesh::detail::shape_type make_shape(pybind11::object const & shape_in)
...
+
+template <typename T>
+struct convert_to_std<Complex<T>>
+{
+    using type = std::complex<T>;
+};
+
+template <typename T>
+using convert_to_std_t = typename convert_to_std<T>::type;
+
```
Comment (ThreeMonth03) [inline cpp/modmesh/buffer/pymod/array_common.hpp:191]: The template could identify not only `modmesh::complex<T>` but also standard type.

File: cpp/modmesh/buffer/pymod/array_common.hpp [hunk 5]
```diff
@@ -211,21 +226,33 @@ class ArrayPropertyHelper
...
             // sarr[K] = V
             if (py::isinstance<py::int_>(py_key) && is_number)
             {
                 const auto key = py_key.cast<ssize_t>();
-
+                if (is_complex_v<T> && py::isinstance(py_value, complex_class))
+                {
+                    arr_out.at(key) = py_value.cast<convert_to_std_t<T>>();
+                    return;
+                }
```
Comment (ThreeMonth03) [inline cpp/modmesh/buffer/pymod/array_common.hpp:242]: Remove `if constexpr`.

**Review by ThreeMonth03 — COMMENTED** [review]
> * [x]  Balance the if/else to improve readability for the value assignment.
> * [x]  Write an informative summary in the commit log.

@yungyuc Please review this pull request again. Thanks.

File: cpp/modmesh/buffer/pymod/array_common.hpp (hunk 5 above)
Comment (yungyuc) [reply cpp/modmesh/buffer/pymod/array_common.hpp:242]: Please balance if/else as I mentioned in the previous review:

```cpp
if (/* ... */)
{
    // ...
}
else
{
    // ...
}
```

The early `return` should be factored outside the branch.

**Review by yungyuc — CHANGES_REQUESTED** [review]
The commit log looks good, but you did not balance the branch.

File: cpp/modmesh/buffer/pymod/array_common.hpp (hunk 5 above)
Comment (ThreeMonth03) [reply cpp/modmesh/buffer/pymod/array_common.hpp:242]: I notice that if we replace the branch with the following code, it also could work.
```c++
arr_out.at(key) = py_value.cast<convert_to_std_t<T>>();
```
However, if the input is `modmesh::complex<T>`, it casts to `std::complex<T>` at first, then it casts to  `modmesh::complex<T>`. I'm not sure which design is better.

**Review by ThreeMonth03 — COMMENTED** [review]
@yungyuc Please review this pr. Thanks.

File: cpp/modmesh/buffer/pymod/array_common.hpp (hunk 5 above)
Comment (yungyuc) [reply cpp/modmesh/buffer/pymod/array_common.hpp:242]: Interesting.  Right, @j8xixo12 ?

Please study it if you have time.  For now the branching is fine because the cycle cost should be too low to appear in benchmark.

**Review by yungyuc — APPROVED** [review]
LGTM
